[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyrein"
version = "0.1.0"
description = "PyRein is a framework for building games as discrete environments with real-time rendering and interchangeable inputs."
